import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "@/styles/globals.css";
import {Navbar} from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  variable: '--font-primary',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <html lang="en" className="bg-white">
      <body
        className={`${poppins.variable} ${poppins.variable} antialiased bg-white`}
      >
      <Navbar/>
        {children}
      <Footer/>
      </body>
    </html>
    </>
  );
}
